/*
 * Copyright (c) 2025 University Corporation for Atmospheric Research/Unidata
 * See LICENSE for license information.
 */

import java.text.SimpleDateFormat
import java.util.Date

plugins {
  id("java-base-conventions")
  application
}

description = "Provides a graphical interface to the CDM library."

project.extra["project.title"] = "ToolsUI"

dependencies {
  implementation(platform(project(":netcdf-java-platform")))

  implementation(project(":bufr"))
  implementation(project(":cdm-core"))
  implementation(project(":cdm-image"))
  implementation(project(":cdm-misc"))
  implementation(project(":grib"))
  implementation(project(":httpservices"))
  implementation(project(":netcdf4"))
  implementation(project(":opendap"))
  implementation(project(":udunits"))
  implementation(project(":uibase"))
  implementation(project(":waterml"))

  implementation(libs.bounce)
  implementation(libs.jdom2)
  implementation(libs.jgoodies.forms)
  implementation(libs.jfree.jfreechart)
  implementation(libs.findbugs.jsr305)
  implementation(libs.lgooddatepicker)
  implementation(libs.protobuf)
  implementation(libs.re2j)
  implementation(libs.slf4j.api)
  implementation(libs.xmlbeans)

  runtimeOnly(project(":cdm-mcidas"))
  runtimeOnly(project(":cdm-radial"))
  runtimeOnly(project(":cdm-s3"))
  runtimeOnly(project(":cdm-zarr"))
  runtimeOnly(project(":dap4"))
  runtimeOnly(project(":libaec-native"))

  runtimeOnly(libs.logback.classic)

  testImplementation(platform(project(":netcdf-java-testing-platform")))

  testImplementation(project(":cdm-test-utils"))

  testCompileOnly(libs.junit4)

  testRuntimeOnly(libs.junit5.platformLauncher)
  testRuntimeOnly(libs.junit5.vintageEngine)
}

application { mainClass = "ucar.nc2.ui.ToolsUI" }

tasks.jar { manifest { attributes["Main-Class"] = "ucar.nc2.ui.ToolsUI" } }

val getBuildInfo =
  tasks.register<WriteProperties>("getBuildInfo") {
    destinationFile = getLayout().buildDirectory.file("resources/main/toolsui.properties")
    comment = "Application configuration generated by Gradle"
    encoding = "UTF-8"
    property("toolsui.version", project.version)
    val iso8601Format = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ")
    property("toolsui.buildTimestamp", iso8601Format.format(Date()))
  }

tasks.processResources { finalizedBy(getBuildInfo) }

tasks.compileJava { dependsOn(getBuildInfo) }
