on: [pull_request]

jobs:
  netcdf-java-tests:
    name: netCDF-Java Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest 8, 11, 17, 21 of zulu and temurin java
        java-version: [8, 11, 17, 21]
        java-vendor: ['zulu', 'temurin', 'corretto']
    steps:
      - uses: actions/checkout@v4
      - name: Build with ${{ matrix.java-vendor }} 17 and run tests with ${{ matrix.java-vendor }} ${{ matrix.java-version }}
        uses: Unidata/thredds-test-action@v3
        with:
          java-vendor: ${{ matrix.java-vendor }}
          java-version: 17
          build-tool: 'gradlew'
          test-command: '-Dorg.gradle.java.installations.fromEnv=JDK8 --info --stacktrace test'
        env:
          JDK8: /usr/thredds-test-environment/${{ matrix.java-vendor }}8
      - name: Prep for artifact upload
        if: failure()
        run: rm -rf build-logic/build/tmp
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: netCDF-Java_JUnit_Results_${{ github.sha }}_${{ matrix.java-vendor }}-${{ matrix.java-version }}
          path: |
            ${{ github.workspace }}/**/build/reports/tests/**/*
